export interface Gig {
  date: string;
  description: string;
  location: string;
  venueEvent: string;
}

export const gigs: Gig[] = [
  {
    date: '2021-09-12',
    description: 'Ecstatic Dance',
    location: 'Amsterdam, NL',
    venueEvent: 'ReMo Studio',
  },
  {
    date: '2021-09-18',
    description: 'Ecstatic Dance',
    location: 'NA',
    venueEvent: 'Wijland Festival',
  },
  {
    date: '2021-10-31',
    description: 'Haloween Ecstatic Dance',
    location: 'Amsterdam, NL',
    venueEvent: 'ReMo Studio',
  },
  {
    date: '2021-11-14',
    description: 'Sunday',
    location: 'Amsterdam, NL',
    venueEvent: 'Odessa Veemkade',
  },
  {
    date: '2021-11-24',
    description: 'Wednesday',
    location: 'Amsterdam, NL',
    venueEvent: 'Odessa Veemkade',
  },
  {
    date: '2021-12-04',
    description: 'Saturday',
    location: 'Amsterdam, NL',
    venueEvent: 'Odessa Veemkade',
  },
  {
    date: '2022-01-21',
    description: 'Friday Cacao',
    location: 'Amsterdam, NL',
    venueEvent: 'Odessa Veemkade',
  },
  {
    date: '2022-01-28',
    description: 'Friday Cacao',
    location: 'Amsterdam, NL',
    venueEvent: 'Odessa Veemkade',
  },
  {
    date: '2022-01-29',
    description: 'Playground',
    location: 'Amsterdam, NL',
    venueEvent: 'Odessa Muiderpoort',
  },
  {
    date: '2022-02-05',
    description: 'Playground',
    location: 'Amsterdam, NL',
    venueEvent: 'Odessa Muiderpoort',
  },
  {
    date: '2022-02-11',
    description: 'Friday',
    location: 'Amsterdam, NL',
    venueEvent: 'Odessa Muiderpoort',
  },
  {
    date: '2022-02-18',
    description: 'Friday Cacao',
    location: 'Amsterdam, NL',
    venueEvent: 'Odessa Veemkade',
  },
  {
    date: '2022-03-05',
    description: 'Playground',
    location: 'Amsterdam, NL',
    venueEvent: 'Odessa Muiderpoort',
  },
  {
    date: '2022-03-11',
    description: 'Friday',
    location: 'Amsterdam, NL',
    venueEvent: 'Odessa Muiderpoort',
  },
  {
    date: '2022-03-12',
    description: 'Saturday',
    location: 'Amsterdam, NL',
    venueEvent: 'Odessa Veemkade',
  },
  {
    date: '2022-03-19',
    description: 'Saturday',
    location: 'Amsterdam, NL',
    venueEvent: 'Odessa Veemkade',
  },
  {
    date: '2022-03-23',
    description: 'Wednesday',
    location: 'Amsterdam, NL',
    venueEvent: 'Odessa Veemkade',
  },
  {
    date: '2022-04-02',
    description: 'Saturday',
    location: 'Amsterdam, NL',
    venueEvent: 'Odessa Veemkade',
  },
  {
    date: '2022-04-15',
    description: 'Friday',
    location: 'Amsterdam, NL',
    venueEvent: 'Odessa Muiderpoort',
  },
  {
    date: '2022-05-21',
    description: 'ZIN Weekender',
    location: 'Recreatieterrein Lingebos',
    venueEvent: 'De Lievelinge',
  },
  {
    date: '2022-05-25',
    description: 'Wednesday',
    location: 'Amsterdam, NL',
    venueEvent: 'Odessa Veemkade',
  },
  {
    date: '2022-06-05',
    description: 'Sunday',
    location: 'Amsterdam, NL',
    venueEvent: 'Odessa Veemkade',
  },
  {
    date: '2022-06-10',
    description: 'Friday',
    location: 'Amsterdam, NL',
    venueEvent: 'Odessa Muiderpoort',
  },
  {
    date: '2022-06-17',
    description: 'Friday Cacao',
    location: 'Amsterdam, NL',
    venueEvent: 'Odessa Veemkade',
  },
  {
    date: '2022-06-24',
    description: 'Wanderweld Festival',
    location: 'Recreatieterrein Lingebos',
    venueEvent: 'De Lievelinge',
  },
  {
    date: '2022-06-25',
    description: 'Saturday',
    location: 'Amsterdam, NL',
    venueEvent: 'Odessa Veemkade',
  },
  {
    date: '2022-07-06',
    description: 'Wednesday',
    location: 'Amsterdam, NL',
    venueEvent: 'Odessa Veemkade',
  },
  {
    date: '2022-07-10',
    description: 'Kids Ecstatic Dance',
    location: 'Amsterdam, NL',
    venueEvent: 'Odessa Muiderpoort',
  },
  {
    date: '2022-07-21',
    description: 'Thursday',
    location: 'Amsterdam, NL',
    venueEvent: 'Odessa Muiderpoort',
  },
  {
    date: '2022-07-23',
    description: 'Playground',
    location: 'Amsterdam, NL',
    venueEvent: 'Odessa Muiderpoort',
  },
  {
    date: '2022-07-31',
    description: 'Kids Ecstatic Dance',
    location: 'Amsterdam, NL',
    venueEvent: 'Odessa Muiderpoort',
  },
  {
    date: '2022-08-04',
    description: 'Thursday',
    location: 'Amsterdam, NL',
    venueEvent: 'Odessa Muiderpoort',
  },
  {
    date: '2022-08-10',
    description: 'Community Ecstatic Dance',
    location: 'Ottermeer, NL',
    venueEvent: 'Landgoed Ottermeer',
  },
  {
    date: '2022-08-13',
    description: 'Saturday',
    location: 'Amsterdam, NL',
    venueEvent: 'Odessa Veemkade',
  },
  {
    date: '2022-08-24',
    description: 'Wednesday',
    location: 'Amsterdam, NL',
    venueEvent: 'Odessa Veemkade',
  },
  {
    date: '2022-09-01',
    description: '2022',
    location: 'Ottermeer, NL',
    venueEvent: 'Het Grote Fijne Festival',
  },
  {
    date: '2022-09-17',
    description: 'Playground',
    location: 'Amsterdam, NL',
    venueEvent: 'Odessa Muiderpoort',
  },
  {
    date: '2022-10-02',
    description: 'Saturday',
    location: 'Amsterdam, NL',
    venueEvent: 'Odessa Veemkade',
  },
  {
    date: '2022-10-22',
    description: 'Wilmer 48 Buto',
    location: 'Amsterdam, NL',
    venueEvent: 'ReMo Studio',
  },
  {
    date: '2022-10-28',
    description: 'Friday',
    location: 'Amsterdam, NL',
    venueEvent: 'Odessa Muiderpoort',
  },
  {
    date: '2022-12-10',
    description: 'Playground',
    location: 'Amsterdam, NL',
    venueEvent: 'Odessa Muiderpoort',
  },
  {
    date: '2023-01-10',
    description: 'Playground',
    location: 'Amsterdam, NL',
    venueEvent: 'Odessa Muiderpoort',
  },
  {
    date: '2023-01-15',
    description: 'Sunday',
    location: 'Amsterdam, NL',
    venueEvent: 'Odessa Veemkade',
  },
  {
    date: '2023-01-25',
    description: 'Wednesday',
    location: 'Amsterdam, NL',
    venueEvent: 'Odessa Veemkade',
  },
  {
    date: '2023-02-09',
    description: 'Thursday',
    location: 'Amsterdam, NL',
    venueEvent: 'Odessa Veemkade',
  },
  {
    date: '2023-02-19',
    description: 'Sunday',
    location: 'Amsterdam, NL',
    venueEvent: 'Odessa Veemkade',
  },
  {
    date: '2023-07-18',
    description: 'Tuesday',
    location: 'Amsterdam, NL',
    venueEvent: 'Odessa Muiderpoort',
  },
  {
    date: '2023-07-19',
    description: 'Wednesday',
    location: 'Amsterdam, NL',
    venueEvent: 'Odessa Veemkade',
  },
  {
    date: '2023-07-25',
    description: 'Tuesday',
    location: 'Amsterdam, NL',
    venueEvent: 'Odessa Muiderpoort',
  },
  {
    date: '2023-07-28',
    description: 'Friday Cacao',
    location: 'Amsterdam, NL',
    venueEvent: 'Odessa Veemkade',
  },
  {
    date: '2023-08-03',
    description: 'Thursday',
    location: 'Amsterdam, NL',
    venueEvent: 'Odessa Veemkade',
  },
  {
    date: '2023-09-01',
    description: 'Friday Cacao',
    location: 'Amsterdam, NL',
    venueEvent: 'Odessa Veemkade',
  },
  {
    date: '2023-09-07',
    description: '2023',
    location: 'Landgoed Energy Up',
    venueEvent: 'Het Grote Fijne Festival',
  },
  {
    date: '2023-09-02',
    description: 'Tuesday',
    location: 'Amsterdam, NL',
    venueEvent: 'Odessa Muiderpoort',
  },
  {
    date: '2023-09-12',
    description: 'Tuesday',
    location: 'Amsterdam, NL',
    venueEvent: 'Odessa Muiderpoort',
  },
  {
    date: '2023-09-15',
    description: 'Friday Cacao',
    location: 'Amsterdam, NL',
    venueEvent: 'Odessa Veemkade',
  },
  {
    date: '2023-09-20',
    description: 'Wednesday',
    location: 'Amsterdam, NL',
    venueEvent: 'Odessa Veemkade',
  },
  {
    date: '2023-10-01',
    description: 'Sunday',
    location: 'Amsterdam, NL',
    venueEvent: 'Odessa Veemkade',
  },
  {
    date: '2023-10-21',
    description: 'Saturday',
    location: 'Amsterdam, NL',
    venueEvent: 'Odessa Veemkade',
  },
  {
    date: '2023-11-22',
    description: 'Wednesday',
    location: 'Amsterdam, NL',
    venueEvent: 'Odessa Veemkade',
  },
  {
    date: '2023-11-26',
    description: 'Sunday',
    location: 'Amsterdam, NL',
    venueEvent: 'Odessa Veemkade',
  },
  {
    date: '2023-12-07',
    description: 'Thursday',
    location: 'Amsterdam, NL',
    venueEvent: 'Odessa Veemkade',
  },
  {
    date: '2023-12-10',
    description: 'Sunday',
    location: 'Amsterdam, NL',
    venueEvent: 'Odessa Veemkade',
  },
  {
    date: '2023-12-17',
    description: 'Sunday',
    location: 'Amsterdam, NL',
    venueEvent: 'Odessa Veemkade',
  },
  {
    date: '2023-12-31',
    description: 'New Year Party',
    location: 'Amsterdam, NL',
    venueEvent: 'Odessa Muiderpoort',
  },
  {
    date: '2024-01-12',
    description: 'Friday Cacao',
    location: 'Amsterdam, NL',
    venueEvent: 'Odessa Veemkade',
  },
  {
    date: '2024-01-21',
    description: 'Sunday',
    location: 'Amsterdam, NL',
    venueEvent: 'Odessa Veemkade',
  },
  {
    date: '2024-01-24',
    description: 'Wednesday',
    location: 'Amsterdam, NL',
    venueEvent: 'Odessa Veemkade',
  },
  {
    date: '2024-02-04',
    description: 'Sunday',
    location: 'Amsterdam, NL',
    venueEvent: 'Odessa Veemkade',
  },
  {
    date: '2024-02-21',
    description: 'WEDance',
    location: 'The Big Island, Hawaii',
    venueEvent: 'Sundari Dance Temple, Hawaii',
  },
  {
    date: '2024-02-29',
    description: 'Thursday',
    location: 'Amsterdam, NL',
    venueEvent: 'Odessa Veemkade',
  },
  {
    date: '2024-03-10',
    description: 'Sunday',
    location: 'Amsterdam, NL',
    venueEvent: 'Odessa Veemkade',
  },
  {
    date: '2024-03-16',
    description: 'Saturday',
    location: 'Amsterdam, NL',
    venueEvent: 'Odessa Veemkade',
  },
  {
    date: '2024-03-17',
    description: 'Saturday',
    location: 'Amsterdam, NL',
    venueEvent: 'Odessa Veemkade',
  },
  {
    date: '2024-03-20',
    description: 'Wednesday',
    location: 'Amsterdam, NL',
    venueEvent: 'Odessa Veemkade',
  },
  {
    date: '2024-04-05',
    description: 'Friday Cacao',
    location: 'Amsterdam, NL',
    venueEvent: 'Odessa Veemkade',
  },
  {
    date: '2024-04-21',
    description: 'Sunday',
    location: 'Amsterdam, NL',
    venueEvent: 'Odessa Veemkade',
  },
];
