export interface Gig {
  date: string;
  event: string;
  location: string;
  venue: string;
  country: string;
}

export const gigs: Gig[] = [
  {
    date: '2021-09-12',
    event: 'Community ED',
    location: 'NL',
    venue: 'ReMo Studio',
    country: 'NL',
  },
  {
    date: '2021-09-18',
    event: `Festival '21 ED`,
    location: 'NL',
    venue: 'Wijland Festival',
    country: 'NL',
  },
  {
    date: '2021-10-31',
    event: 'Haloween ED',
    location: 'NL',
    venue: 'ReMo Studio',
    country: 'NL',
  },
  {
    date: '2021-11-14',
    event: 'Sunday ED | Veemkade',
    location: 'NL',
    venue: 'Odessa Amsterdam',
    country: 'NL',
  },
  {
    date: '2021-11-24',
    event: 'Wednesday ED | Veemkade',
    location: 'NL',
    venue: 'Odessa Amsterdam',
    country: 'NL',
  },
  {
    date: '2021-12-04',
    event: 'Saturday ED | Veemkade',
    location: 'NL',
    venue: 'Odessa Amsterdam',
    country: 'NL',
  },
  {
    date: '2022-01-21',
    event: 'Friday Cacao ED | Veemkade',
    location: 'NL',
    venue: 'Odessa Amsterdam',
    country: 'NL',
  },
  {
    date: '2022-01-28',
    event: 'Friday Cacao ED | Veemkade',
    location: 'NL',
    venue: 'Odessa Amsterdam',
    country: 'NL',
  },
  {
    date: '2022-01-29',
    event: 'Playground ED | Muiderpoort',
    location: 'NL',
    venue: 'Odessa Amsterdam',
    country: 'NL',
  },
  {
    date: '2022-02-05',
    event: 'Playground ED | Muiderpoort',
    location: 'NL',
    venue: 'Odessa Amsterdam',
    country: 'NL',
  },
  {
    date: '2022-02-11',
    event: 'Friday ED | Muiderpoort',
    location: 'NL',
    venue: 'Odessa Amsterdam',
    country: 'NL',
  },
  {
    date: '2022-02-18',
    event: 'Friday Cacao ED | Veemkade',
    location: 'NL',
    venue: 'Odessa Amsterdam',
    country: 'NL',
  },
  {
    date: '2022-03-05',
    event: 'Playground ED | Muiderpoort',
    location: 'NL',
    venue: 'Odessa Amsterdam',
    country: 'NL',
  },
  {
    date: '2022-03-11',
    event: 'Friday ED | Muiderpoort',
    location: 'NL',
    venue: 'Odessa Amsterdam',
    country: 'NL',
  },
  {
    date: '2022-03-12',
    event: 'Saturday ED | Veemkade',
    location: 'NL',
    venue: 'Odessa Amsterdam',
    country: 'NL',
  },
  {
    date: '2022-03-19',
    event: 'Saturday ED | Veemkade',
    location: 'NL',
    venue: 'Odessa Amsterdam',
    country: 'NL',
  },
  {
    date: '2022-03-23',
    event: 'Wednesday ED | Veemkade',
    location: 'NL',
    venue: 'Odessa Amsterdam',
    country: 'NL',
  },
  {
    date: '2022-04-02',
    event: 'Saturday ED | Veemkade',
    location: 'NL',
    venue: 'Odessa Amsterdam',
    country: 'NL',
  },
  {
    date: '2022-04-15',
    event: 'Friday ED | Muiderpoort',
    location: 'NL',
    venue: 'Odessa Amsterdam',
    country: 'NL',
  },
  {
    date: '2022-05-21',
    event: 'ZIN Weekender',
    location: 'Het Lingebos',
    venue: 'De Lievelinge',
    country: 'NL',
  },
  {
    date: '2022-05-25',
    event: 'Wednesday ED | Veemkade',
    location: 'NL',
    venue: 'Odessa Amsterdam',
    country: 'NL',
  },
  {
    date: '2022-06-05',
    event: 'Sunday ED | Veemkade',
    location: 'NL',
    venue: 'Odessa Amsterdam',
    country: 'NL',
  },
  {
    date: '2022-06-10',
    event: 'Friday ED | Muiderpoort',
    location: 'NL',
    venue: 'Odessa Amsterdam',
    country: 'NL',
  },
  {
    date: '2022-06-17',
    event: 'Friday Cacao ED | Veemkade',
    location: 'NL',
    venue: 'Odessa Amsterdam',
    country: 'NL',
  },
  {
    date: '2022-06-24',
    event: 'Wanderweld Festival',
    location: 'Recreatieterrein Lingebos',
    venue: 'De Lievelinge',
    country: 'NL',
  },
  {
    date: '2022-06-25',
    event: 'Saturday ED | Veemkade',
    location: 'NL',
    venue: 'Odessa Amsterdam',
    country: 'NL',
  },
  {
    date: '2022-07-06',
    event: 'Wednesday ED | Veemkade',
    location: 'NL',
    venue: 'Odessa Amsterdam',
    country: 'NL',
  },
  {
    date: '2022-07-10',
    event: 'Kids ED',
    location: 'NL',
    venue: 'Odessa Amsterdam',
    country: 'NL',
  },
  {
    date: '2022-07-21',
    event: 'Thursday ED | Muiderpoort',
    location: 'NL',
    venue: 'Odessa Amsterdam',
    country: 'NL',
  },
  {
    date: '2022-07-23',
    event: 'Playground ED | Muiderpoort',
    location: 'NL',
    venue: 'Odessa Amsterdam',
    country: 'NL',
  },
  {
    date: '2022-07-31',
    event: 'Kids ED | Muiderpoort',
    location: 'NL',
    venue: 'Odessa Amsterdam',
    country: 'NL',
  },
  {
    date: '2022-08-04',
    event: 'Thursday ED | Muiderpoort',
    location: 'NL',
    venue: 'Odessa Amsterdam',
    country: 'NL',
  },
  {
    date: '2022-08-10',
    event: 'Community ED',
    location: 'NL',
    venue: 'Ottermeer',
    country: 'NL',
  },
  {
    date: '2022-08-13',
    event: 'Saturday ED | Veemkade',
    location: 'NL',
    venue: 'Odessa Amsterdam',
    country: 'NL',
  },
  {
    date: '2022-08-24',
    event: 'Wednesday ED | Veemkade',
    location: 'NL',
    venue: 'Odessa Amsterdam',
    country: 'NL',
  },
  {
    date: '2022-09-01',
    event: `Grote Fijne Festival '22`,
    location: 'NL',
    venue: 'ED Festival Holland',
    country: 'NL',
  },
  {
    date: '2022-09-17',
    event: 'Playground ED | Muiderpoort',
    location: 'NL',
    venue: 'Odessa Amsterdam',
    country: 'NL',
  },
  {
    date: '2022-10-02',
    event: 'Saturday ED | Veemkade',
    location: 'NL',
    venue: 'Odessa Amsterdam',
    country: 'NL',
  },
  {
    date: '2022-10-22',
    event: `Wilmer's 49th ED`,
    location: 'NL',
    venue: 'ReMo Studio',
    country: 'NL',
  },
  {
    date: '2022-10-28',
    event: 'Friday ED | Muiderpoort',
    location: 'NL',
    venue: 'Odessa Amsterdam',
    country: 'NL',
  },
  {
    date: '2022-12-10',
    event: 'Playground ED | Muiderpoort',
    location: 'NL',
    venue: 'Odessa Amsterdam',
    country: 'NL',
  },
  {
    date: '2023-01-10',
    event: 'Playground ED | Muiderpoort',
    location: 'NL',
    venue: 'Odessa Amsterdam',
    country: 'NL',
  },
  {
    date: '2023-01-15',
    event: 'Sunday ED | Veemkade',
    location: 'NL',
    venue: 'Odessa Amsterdam',
    country: 'NL',
  },
  {
    date: '2023-01-25',
    event: 'Wednesday ED | Veemkade',
    location: 'NL',
    venue: 'Odessa Amsterdam',
    country: 'NL',
  },
  {
    date: '2023-02-09',
    event: 'Thursday ED | Veemkade',
    location: 'NL',
    venue: 'Odessa Amsterdam',
    country: 'NL',
  },
  {
    date: '2023-02-19',
    event: 'Sunday ED | Veemkade',
    location: 'NL',
    venue: 'Odessa Amsterdam',
    country: 'NL',
  },
  {
    date: '2023-07-18',
    event: 'Tuesday ED | Muiderpoort',
    location: 'NL',
    venue: 'Odessa Amsterdam',
    country: 'NL',
  },
  {
    date: '2023-07-19',
    event: 'Wednesday ED | Veemkade',
    location: 'NL',
    venue: 'Odessa Amsterdam',
    country: 'NL',
  },
  {
    date: '2023-07-25',
    event: 'Tuesday ED | Muiderpoort',
    location: 'NL',
    venue: 'Odessa Amsterdam',
    country: 'NL',
  },
  {
    date: '2023-07-28',
    event: 'Friday Cacao ED | Veemkade',
    location: 'NL',
    venue: 'Odessa Amsterdam',
    country: 'NL',
  },
  {
    date: '2023-08-03',
    event: 'Thursday ED | Veemkade',
    location: 'NL',
    venue: 'Odessa Amsterdam',
    country: 'NL',
  },
  {
    date: '2023-09-01',
    event: 'Friday Cacao ED | Veemkade',
    location: 'NL',
    venue: 'Odessa Amsterdam',
    country: 'NL',
  },
  {
    date: '2023-09-07',
    event: `Grote Fijne Festival '23`,
    location: 'NL',
    venue: 'ED Festival Holland',
    country: 'NL',
  },
  {
    date: '2023-09-02',
    event: 'Tuesday ED | Muiderpoort',
    location: 'NL',
    venue: 'Odessa Amsterdam',
    country: 'NL',
  },
  {
    date: '2023-09-12',
    event: 'Tuesday ED | Muiderpoort',
    location: 'NL',
    venue: 'Odessa Amsterdam',
    country: 'NL',
  },
  {
    date: '2023-09-15',
    event: 'Friday Cacao ED | Veemkade',
    location: 'NL',
    venue: 'Odessa Amsterdam',
    country: 'NL',
  },
  {
    date: '2023-09-20',
    event: 'Wednesday ED | Veemkade',
    location: 'NL',
    venue: 'Odessa Amsterdam',
    country: 'NL',
  },
  {
    date: '2023-10-01',
    event: 'Sunday ED | Veemkade',
    location: 'NL',
    venue: 'Odessa Amsterdam',
    country: 'NL',
  },
  {
    date: '2023-10-21',
    event: 'Saturday ED | Veemkade',
    location: 'NL',
    venue: 'Odessa Amsterdam',
    country: 'NL',
  },
  {
    date: '2023-11-22',
    event: 'Wednesday ED | Veemkade',
    location: 'NL',
    venue: 'Odessa Amsterdam',
    country: 'NL',
  },
  {
    date: '2023-11-26',
    event: 'Sunday ED | Veemkade',
    location: 'NL',
    venue: 'Odessa Amsterdam',
    country: 'NL',
  },
  {
    date: '2023-12-07',
    event: 'Thursday ED | Veemkade',
    location: 'NL',
    venue: 'Odessa Amsterdam',
    country: 'NL',
  },
  {
    date: '2023-12-10',
    event: 'Sunday ED | Veemkade',
    location: 'NL',
    venue: 'Odessa Amsterdam',
    country: 'NL',
  },
  {
    date: '2023-12-17',
    event: 'Sunday ED | Veemkade',
    location: 'NL',
    venue: 'Odessa Amsterdam',
    country: 'NL',
  },
  {
    date: '2023-12-31',
    event: 'NYE ED | Muiderpoort',
    location: 'NL',
    venue: 'Odessa Amsterdam',
    country: 'NL',
  },
  {
    date: '2024-01-07',
    event: `EDFH Winter After Party '24`,
    location: 'NL',
    venue: 'ED Festival Holland',
    country: 'NL',
  },
  {
    date: '2024-01-12',
    event: 'Friday Cacao ED | Veemkade',
    location: 'NL',
    venue: 'Odessa Amsterdam',
    country: 'NL',
  },
  {
    date: '2024-01-21',
    event: 'Sunday ED | Veemkade',
    location: 'NL',
    venue: 'Odessa Amsterdam',
    country: 'NL',
  },
  {
    date: '2024-01-24',
    event: 'Wednesday ED | Veemkade',
    location: 'NL',
    venue: 'Odessa Amsterdam',
    country: 'NL',
  },
  {
    date: '2024-02-04',
    event: 'Sunday ED | Veemkade',
    location: 'NL',
    venue: 'Odessa Amsterdam',
    country: 'NL',
  },
  {
    date: '2024-02-21',
    event: ' ED @ Sundari',
    location: 'Hawaii, USA',
    venue: 'WEDance',
    country: 'USA',
  },
  {
    date: '2024-02-29',
    event: 'Thursday ED | Veemkade',
    location: 'NL',
    venue: 'Odessa Amsterdam',
    country: 'NL',
  },
  {
    date: '2024-03-10',
    event: 'Sunday ED | Veemkade',
    location: 'NL',
    venue: 'Odessa Amsterdam',
    country: 'NL',
  },
  {
    date: '2024-03-16',
    event: 'Saturday ED | Veemkade',
    location: 'NL',
    venue: 'Odessa Amsterdam',
    country: 'NL',
  },
  {
    date: '2024-03-17',
    event: 'ED @ BlueBirds',
    location: 'NL',
    venue: 'Haarlem',
    country: 'NL',
  },
  {
    date: '2024-03-27',
    event: 'Wednesday ED | Veemkade',
    location: 'NL',
    venue: 'Odessa Amsterdam',
    country: 'NL',
  },
  {
    date: '2024-04-06',
    event: 'Saturday ED | Veemkade',
    location: 'NL',
    venue: 'Odessa Amsterdam',
    country: 'NL',
  },
  {
    date: '2024-04-21',
    event: 'Sunday ED | Veemkade',
    location: 'NL',
    venue: 'Odessa Amsterdam',
    country: 'NL',
  },
  {
    date: '2024-04-28',
    event: 'Sunday ED | Veemkade',
    location: 'NL',
    venue: 'Odessa Amsterdam',
    country: 'NL',
  },
  {
    date: '2024-05-03',
    event: 'ED Leiden',
    location: 'NL',
    venue: 'ED Leiden',
    country: 'NL',
  },
  {
    date: '2024-05-09',
    event: 'Thursday ED | Veemkade',
    location: 'NL',
    venue: 'Odessa Amsterdam',
    country: 'NL',
  },
  {
    date: '2024-05-18',
    event: 'Bezweefd ED @ OASE',
    location: 'NL',
    venue: 'Rotterdam',
    country: 'NL',
  },
  {
    date: '2024-06-20',
    event: 'Thursday ED | Veemkade',
    location: 'NL',
    venue: 'Odessa Amsterdam',
    country: 'NL',
  },
  {
    date: '2024-06-29',
    event: 'Saturday ED | Veemkade',
    location: 'NL',
    venue: 'Odessa Amsterdam',
    country: 'NL',
  },
  {
    date: '2024-07-07',
    event: 'Sunday ED | Veemkade',
    location: 'NL',
    venue: 'Odessa Amsterdam',
    country: 'NL',
  },
  {
    date: '2024-07-10',
    event: `EDFH Basement Set '24`,
    location: 'NL',
    venue: 'ED Festival Holland',
    country: 'NL',
  },
  {
    date: '2024-07-19',
    event: 'Friday ED | Veemkade',
    location: 'NL',
    venue: 'Odessa Amsterdam',
    country: 'NL',
  },
  {
    date: '2024-07-26',
    event: 'Friday ED | Veemkade',
    location: 'NL',
    venue: 'Odessa Amsterdam',
    country: 'NL',
  },
  {
    date: '2024-08-15',
    event: 'Thursday ED | Veemkade',
    location: 'NL',
    venue: 'Odessa Amsterdam',
    country: 'NL',
  },
  {
    date: '2024-08-15',
    event: `Landjuweel '24'`,
    location: 'NL',
    venue: 'Ruigoord',
    country: 'NL',
  },
  {
    date: '2024-08-30',
    event: 'Friday ED | Veemkade',
    location: 'NL',
    venue: 'Odessa Amsterdam',
    country: 'NL',
  },
  {
    date: '2024-08-31',
    event: 'Saturday ED | Veemkade',
    location: 'NL',
    venue: 'Odessa Amsterdam',
    country: 'NL',
  },
  {
    date: '2024-09-05',
    event: 'Thursday ED | Veemkade',
    location: 'NL',
    venue: 'Odessa Amsterdam',
    country: 'NL',
  },
  {
    date: '2024-09-29',
    event: 'Sunday ED | Veemkade',
    location: 'NL',
    venue: 'Odessa Amsterdam',
    country: 'NL',
  },
  {
    date: '2024-10-04',
    event: 'ED',
    location: 'ED Leiden',
    venue: 'ED Leiden',
    country: 'NL',
  },
  {
    date: '2024-10-06',
    event: 'Queerstatic | Veemkade',
    location: 'NL',
    venue: 'Odessa Amsterdam',
    country: 'NL',
  },
  {
    date: '2024-10-09',
    event: 'Wednesday ED | Veemkade',
    location: 'NL',
    venue: 'Odessa Amsterdam',
    country: 'NL',
  },
  {
    date: '2024-10-25',
    event: 'Wednesday ED | Veemkade',
    location: 'NL',
    venue: 'Odessa Amsterdam',
    country: 'NL',
  },
  {
    date: '2024-10-31',
    event: 'Friday ED | Veemkade',
    location: 'NL',
    venue: 'Odessa Amsterdam',
    country: 'NL',
  },
  {
    date: '2024-11-10',
    event: 'Sunday ED | Veemkade',
    location: 'NL',
    venue: 'Odessa Amsterdam',
    country: 'NL',
  },
  {
    date: '2024-11-13',
    event: 'Wednesday ED | Veemkade',
    location: 'NL',
    venue: 'Odessa Amsterdam',
    country: 'NL',
  },
  {
    date: '2024-11-16',
    event: 'Ecstatic Rave',
    location: 'NL',
    venue: 'Ambrosia',
    country: 'NL',
  },
  {
    date: '2024-11-27',
    event: 'Wednesday ED | Veemkade',
    location: 'NL',
    venue: 'Odessa Amsterdam',
    country: 'NL',
  },
  {
    date: '2024-11-13',
    event: 'Friday ED | Veemkade',
    location: 'NL',
    venue: 'Odessa Amsterdam',
    country: 'NL',
  },
  {
    date: '2024-12-29',
    event: 'Sunday ED | Veemkade',
    location: 'NL',
    venue: 'Odessa Amsterdam',
    country: 'NL',
  },

  {
    date: '2024-12-31',
    event: 'NYE ED',
    location: 'NL',
    venue: 'Odessa Amsterdam',
    country: 'NL',
  },
  {
    date: '2025-01-31',
    event: ' Sensual ED @ Shivari',
    location: 'Koh Phangan, Thailand',
    venue: 'Shivari',
    country: 'TH',
  },
  {
    date: '2025-02-16',
    event: ' Sunday ED @ Kalani',
    location: 'Hawaii, USA',
    venue: 'Kalani',
    country: 'USA',
  },
  {
    date: '2025-02-19',
    event: ' ED @ Sundari',
    location: 'Hawaii, USA',
    venue: 'WEDance',
    country: 'USA',
  },
  {
    date: '2025-03-14',
    event: 'Friday ED | Veemkade',
    location: 'NL',
    venue: 'Odessa Amsterdam',
    country: 'NL',
  },
  {
    date: '2025-03-29',
    event: 'Saturday ED | Veemkade',
    location: 'NL',
    venue: 'Odessa Amsterdam',
    country: 'NL',
  },
  {
    date: '2025-04-05',
    event: 'Ecstatic Rave',
    location: 'NL',
    venue: 'Ambrosia',
    country: 'NL',
  },
  {
    date: '2025-04-09',
    event: 'Wednesday ED | Veemkade',
    location: 'NL',
    venue: 'Odessa Amsterdam',
    country: 'NL',
  },
  {
    date: '2025-04-20',
    event: 'Sunday ED | Veemkade',
    location: 'NL',
    venue: 'Odessa Amsterdam',
    country: 'NL',
  },
    {
    date: '2025-04-26',
    event: 'Saturday ED | Veemkade',
    location: 'NL',
    venue: 'Odessa Amsterdam',
    country: 'NL',
  },
];
